# Generated by Django 4.2.16 on 2024-11-11 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='end_loc', to='hamsafar.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_loc', to='hamsafar.location'),
        ),
    ]
